#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'strscan'
class Nline
  @linenum
  @str
  def initialize(str,linenum)
    @str = str
    @linenum = linenum
  end
  def +(other)
    Nline.new(@str+other.str, [@linenum,other.linenum].min)
  end
  attr_accessor :linenum, :str
end
class Ndef
  def initialize(word,val)
    @word=word
    @val=val
  end
  attr_accessor :word, :val
end
class Ncond
  def initialize(kind, cond, arg, arg_else)
   @kind = kind
   @cond = cond
   @arg = arg
   @arg_else = arg_else
  end
  def to_s
   return "( #{@kind.to_s}, #{@arg.to_s} )"
  end
  attr_accessor :kind, :cond, :arg, :arg_else
end

class PMK < Racc::Parser

module_eval(<<'...end pmk0.y/module_eval...', 'pmk0.y', 83)

  def trim_comment(str)
      ss = StringScanner.new(str)
      ret = ""
      until ss.eos?
        if s = ss.scan(/\\\\/m) # escape \\
          ret += s
        elsif s = ss.scan(/\\#/m) # escape #
          ret += s
        elsif s = ss.scan(/#/m) # comment begin
          ret += "\n"
          break
        elsif s = ss.scan(/./m) #other
          ret += s
        end
      end
      return ret
  end
  
  def concat_escaped_returns(lines)
    ret_lines=[]
  	oneline =""
  	fnum=0
  	lines.each_with_index{|line,num|
  	    oneline += line
  	    if not line =~ /([^\\]|^)(\\\\)*\\$/
  	      ret_lines << oneline
  	      @real_linenum << fnum
  	      fnum=num+1
  	      oneline = ""
  	    end
  	}
  	ret_lines << oneline
  	return ret_lines
  end

  def real_linenum()
    return @real_linenum
  end
  def parse_all(multilines)
    @real_linenum = []
    @logical_lines = concat_escaped_returns(multilines)
  	@lines = multilines
    @racc_debug_out = STDERR
    @head = true
    @linenum = -1
    @readed = ""
    @in_define = false
    @ss = StringScanner.new("")
    do_parse
  end
  
  def next_token
    return nil if ( @ss.eos? and @linenum == @logical_lines.size-1 )
    ret = 
	    if @ss.eos?
	        @linenum += 1
	    		line = @logical_lines[@linenum]
	        @readed = ""
	        #ƒRƒƒ“ƒg‚Ìˆ—
	        unless ( line =~ /\A\t/m  or @in_define )
	        	line = trim_comment(line)
	        end
	        s =""
	        @ss.string = line
	        [:RET,"\n"]
	    elsif @head and @ss.check(/\s*(ifeq|ifneq|else|endif|define|endef)(\W|\z)/m)
#	      p @ss.string
	    	s = @ss.scan(/\s*(\w+)\s*/m)
	    	s.strip!
	    	mean = Nline.new(s,@linenum)
	    	case s
	        when "ifeq"
	        	  [:COND, mean]
	        when "ifneq"
	        	  [:COND, mean]
	        when "else"
	            [:ELSE, mean]
	        when "endif"
	            [:ENDIF, mean]
	        when "define"
	            @in_define = true
	        	  [:DEF, mean]
	        when "endef"
	            @in_define = false
	        	  [:ENDEF, mean]
        end
	    elsif s = @ss.scan(/[\(\)\,]/m) #symbols
	    		mean = Nline.new(s,@linenum)
	        [s, mean]
	    else
	      s = @ss.scan(/[^\(\)\,]+/m) #other
	    		mean = Nline.new(s,@linenum)
	        [:OTHER, mean]
	    end
	  @readed += s
    @head = ( ret[0] == :RET)
    return ret
  end
  
  
  def on_error(t, val, vstack)
    bgn= [0,@linenum - 15].max
#    p @lines
    for i in bgn..@linenum
      puts (i+1).to_s + ": "+@lines[i]
    end
    puts ""
    puts (@linenum+1).to_s + ": "+@readed +" <here>"
    puts "\nparse error on value #{val.inspect} (#{token_to_str(t)})"
    raise ParseError, ""
  end 

  attr_accessor :yydebug

...end pmk0.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    36,     3,     5,     7,     9,     3,     5,     7,     9,    43,
     1,     3,     5,     7,     9,    11,    19,    26,    15,     1,
     3,     5,     7,     9,    11,    20,    18,    15,     1,     3,
     5,     7,     9,    11,    45,    48,    15,     1,     3,     5,
     7,     9,    11,    29,    22,    15,     1,     3,     5,     7,
     9,    11,    34,    35,    15,     1,     3,     5,     7,     9,
    11,    16,   nil,    15,    36,     3,     5,     7,     9,    31,
   nil,    32,    33,    31,    47,   nil,    33,    31,    46,   nil,
    33,     3,     5,     7,     9 ]

racc_action_check = [
    37,    37,    37,    37,    37,    13,    13,    13,    13,    37,
     0,     0,     0,     0,     0,     0,    10,    16,     0,     4,
     4,     4,     4,     4,     4,    11,     8,     4,    42,    42,
    42,    42,    42,    42,    39,    42,    42,    34,    34,    34,
    34,    34,    34,    24,    12,    34,    28,    28,    28,    28,
    28,    28,    28,    28,    28,    21,    21,    21,    21,    21,
    21,     2,   nil,    21,    29,    29,    29,    29,    29,    27,
   nil,    27,    27,    41,    41,   nil,    41,    40,    40,   nil,
    40,    15,    15,    15,    15 ]

racc_action_pointer = [
     8,   nil,    61,   nil,    17,   nil,   nil,   nil,    24,   nil,
    14,    22,    42,     2,   nil,    78,    17,   nil,   nil,   nil,
   nil,    53,   nil,   nil,    41,   nil,   nil,    66,    44,    62,
   nil,   nil,   nil,   nil,    35,   nil,   nil,    -2,   nil,    32,
    74,    70,    26,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -28,    -7,   -28,   -11,    -1,   -12,    -3,   -13,   -28,   -14,
   -28,   -28,   -28,    -8,   -10,   -28,   -28,    -2,    -4,    -5,
   -19,   -28,    -6,    -9,   -28,   -23,    49,   -28,   -28,   -28,
   -18,   -19,   -19,   -21,   -28,   -16,   -27,   -28,   -25,   -28,
   -28,   -28,   -28,   -22,   -24,   -26,   -20,   -17,   -15 ]

racc_goto_table = [
    17,     4,    27,    25,    38,    21,    23,    24,    37,     2,
   nil,   nil,    44,    40,    41,   nil,   nil,    39,   nil,   nil,
   nil,   nil,    28,   nil,    17,    39,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    42,   nil,   nil,    17 ]

racc_goto_check = [
     3,     2,    10,     6,    14,     9,     8,    12,    13,     1,
   nil,   nil,    14,    10,    10,   nil,   nil,     6,   nil,   nil,
   nil,   nil,     2,   nil,     3,     6,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     9,     1,    -4,   nil,   nil,   -12,   nil,    -7,    -6,
   -18,   nil,    -8,   -21,   -25 ]

racc_goto_default = [
   nil,   nil,   nil,     6,     8,    10,    12,    13,    14,   nil,
   nil,    30,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 13, :_reduce_none,
  2, 14, :_reduce_2,
  1, 14, :_reduce_none,
  2, 15, :_reduce_4,
  2, 15, :_reduce_5,
  2, 15, :_reduce_6,
  1, 15, :_reduce_7,
  1, 18, :_reduce_8,
  2, 19, :_reduce_9,
  1, 19, :_reduce_none,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  6, 16, :_reduce_15,
  4, 16, :_reduce_16,
  5, 21, :_reduce_17,
  2, 22, :_reduce_18,
  0, 22, :_reduce_19,
  3, 23, :_reduce_20,
  1, 23, :_reduce_none,
  5, 17, :_reduce_22,
  1, 24, :_reduce_none,
  2, 25, :_reduce_24,
  1, 25, :_reduce_none,
  2, 26, :_reduce_26,
  1, 26, :_reduce_27 ]

racc_reduce_n = 28

racc_shift_n = 49

racc_token_table = {
  false => 0,
  :error => 1,
  :RET => 2,
  "(" => 3,
  ")" => 4,
  "," => 5,
  :OTHER => 6,
  :COND => 7,
  :ELSE => 8,
  :ENDIF => 9,
  :DEF => 10,
  :ENDEF => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "RET",
  "\"(\"",
  "\")\"",
  "\",\"",
  "OTHER",
  "COND",
  "ELSE",
  "ENDIF",
  "DEF",
  "ENDEF",
  "$start",
  "target",
  "many",
  "one",
  "conditions",
  "define",
  "line",
  "line_rcsv",
  "word",
  "in_cond",
  "line_in_cond",
  "word_in_cond",
  "defword",
  "many_in_def",
  "one_in_def" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'pmk0.y', 15)
  def _reduce_2(val, _values, result)
    result=val[0]+val[1]
    result
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'pmk0.y', 18)
  def _reduce_4(val, _values, result)
    result=[val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 19)
  def _reduce_5(val, _values, result)
    result=[val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 20)
  def _reduce_6(val, _values, result)
    result=[val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 21)
  def _reduce_7(val, _values, result)
    result=[]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 23)
  def _reduce_8(val, _values, result)
    result=val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 25)
  def _reduce_9(val, _values, result)
    result = val[0] + val[1]
    result
  end
.,.,

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'pmk0.y', 30)
  def _reduce_15(val, _values, result)
    result = Ncond.new(val[0].str,val[1],val[2],val[4] ) 
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 31)
  def _reduce_16(val, _values, result)
    result = Ncond.new(val[0].str,val[1],val[2], Nline.new("",@linenum) ) 
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 32)
  def _reduce_17(val, _values, result)
    result = [val[1],val[3]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 33)
  def _reduce_18(val, _values, result)
    result= val[0]+val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 34)
  def _reduce_19(val, _values, result)
    result=Nline.new("",@linenum)
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 35)
  def _reduce_20(val, _values, result)
     result=val[0]+val[1]+val[2] 
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'pmk0.y', 38)
  def _reduce_22(val, _values, result)
    result = Ndef.new(val[1],val[3]) 
    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'pmk0.y', 42)
  def _reduce_24(val, _values, result)
    result=val[0]+val[1]
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'pmk0.y', 44)
  def _reduce_26(val, _values, result)
    result=[val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pmk0.y', 45)
  def _reduce_27(val, _values, result)
    result=[]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class PMK


def test
calc = PMK.new
  begin
    str ="ifneq($(RUNTIME_CONF), )\n\techo hoge\nendif"
#    str ="ifneq(a,b)\na=b\\\nc=d\nendif\n"

    puts str
    res =  calc.parse_all(str)
    p "res"
    puts res.inspect
  rescue Racc::ParseError
    puts 'parse error:'
    p calc.tokens
  end
end
#test
